default:
  tags:
    - group16-runner

variables:
  USERNAME: csci5308vm16
  HOST: csci5308-16
  PORT: 22

stages:
  - build
  - deploy

build:
  stage: build
  image: node:16
  script:
   - cd frontend/api-tester
   - npm install
   - npm run build
  artifacts:
    paths:
    # have to check about this path
      - frontend/api-tester/build/

deploy:
  stage: deploy
  script:
    - echo "React deploy started"
    - echo "deployment-key:${DEPLOYMENT_PRIVATE_KEY}"
    - eval $(ssh-agent -s)
    - chmod og-rwx ${DEPLOYMENT_PRIVATE_KEY}
    - ssh -o StrictHostKeyChecking=no -i "${DEPLOYMENT_PRIVATE_KEY}" $USERNAME@$HOST
    # - scp -r -o StrictHostKeyChecking=no -i "${DEPLOYMENT_PRIVATE_KEY}" frontend/api-tester/build/* "$USERNAME@$HOST:/home"
  only:
    - setup-pipeline
  