default:
  tags:
    - deploymentrunner

stages:
  - smells
  - build
  - test
  - deploy

variables:
  USERNAME: csci5308vm16
  HOST: csci5308vm16.research.cs.dal.ca
  PORT: 22

project_smells:
  stage: smells
  script:
    - cd backend
    - mkdir smells/
    - pwd
    - java -jar .gitlab/DesigniteJava.jar -i api-db-tester -o smells/ -d
  artifacts:
    paths:
      - smells/
      - backend/api-db-tester

maven_build:
  stage: build
  image: maven:latest
  script:
    - cd backend/api-db-tester
    - echo "Build started"
    - java -version
    - export JAVA_HOME=/usr/lib/jvm/java-17-oracle
    - mvn -version
    - mvn clean package
  artifacts:
    paths:
      - backend/api-db-tester/target/*.jar

test:
  stage: test
  script:
    - echo "Pipeline test started"
    - cd backend/api-db-tester
    - java -version
    - export JAVA_HOME=/usr/lib/jvm/java-17-oracle
    - mvn -version
    - mvn verify

deploy_main:
  stage: deploy
  artifacts:
    paths:
      - backend/api-db-tester/target/*.jar
  script:
    - echo "Deploying the develop pipeline"
    - eval $(ssh-agent -s)
    - chmod og-rwx ${DEPLOYMENT_PRIVATE_KEY}
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOYMENT_PRIVATE_KEY}" backend/api-db-tester/target/*.jar "$USERNAME@$HOST:/home/${USERNAME}/backend/api-db-tester-0.0.1-SNAPSHOT.jar"
  only:
    - develop

